### ISSUE TITLE
Drop "--privileged" flag from container options

### ISSUE THREAD

**Issue by sfalexrog** [CopterExpress/clever-show-ds#1]
No piece of software that is present in the container should require elevated access (except for `systemd`, but even it should be able to run in non-privileged mode with some tweaking: https://developers.redhat.com/blog/2016/09/13/running-systemd-in-a-non-privileged-container/).

Running a container with `--privileged` access may be considered a security issue by some users.

**Comment by goldarte** [comment]
Thank you for the description of --privileged option, I resolved this issue here: https://github.com/goldarte/clever-show-ds/commit/35c59f9b5f35f40e2034e0c5112152d0275fe32e
